# Generated by Django 5.2.1 on 2025-06-02 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('DFA', 'Déterministe'), ('NFA', 'Non Déterministe'), ('EFA', 'Avec ε-transitions')], default='DFA', max_length=3)),
                ('alphabet', models.CharField(help_text='Ex: a,b,c', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Etat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('est_initial', models.BooleanField(default=False)),
                ('est_final', models.BooleanField(default=False)),
                ('automate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etats', to='automateApp.automate')),
            ],
        ),
        migrations.CreateModel(
            name='ExpressionRationnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('expression', models.TextField(help_text='Utiliser la notation classique: a(b+c)* par exemple')),
                ('alphabet', models.CharField(help_text='Ex: a,b,c', max_length=100)),
                ('automate_associe', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expression_origine', to='automateApp.automate')),
            ],
        ),
        migrations.CreateModel(
            name='LangageRationnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('automate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='langages', to='automateApp.automate')),
                ('expression', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='langages', to='automateApp.expressionrationnelle')),
            ],
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbole', models.CharField(help_text='Ex: a, b, ou ε', max_length=10)),
                ('automate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='automateApp.automate')),
                ('cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_entrantes', to='automateApp.etat')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_sortantes', to='automateApp.etat')),
            ],
        ),
    ]
