# Generated by Django 5.2.1 on 2025-06-13 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automateApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='langagerationnel',
            name='expression',
        ),
        migrations.RemoveField(
            model_name='langagerationnel',
            name='automate',
        ),
        migrations.RemoveField(
            model_name='etat',
            name='est_initial',
        ),
        migrations.RemoveField(
            model_name='transition',
            name='cible',
        ),
        migrations.AddField(
            model_name='automate',
            name='etat_initial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automate_initial', to='automateApp.etat'),
        ),
        migrations.AddField(
            model_name='transition',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transitions_destination', to='automateApp.etat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='automate',
            name='alphabet',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='automate',
            name='type',
            field=models.CharField(choices=[('AFD', 'Automate fini déterministe'), ('AFN', 'Automate fini non déterministe'), ('eAFN', 'Automate fini non déterministe avec epsilon-transitions')], max_length=4),
        ),
        migrations.AlterField(
            model_name='transition',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_source', to='automateApp.etat'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='symbole',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='ExpressionReguliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=200)),
                ('methode_construction', models.CharField(blank=True, choices=[('thompson', 'Thompson'), ('glushkov', 'Glushkov')], max_length=20, null=True)),
                ('automate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automateApp.automate')),
            ],
        ),
        migrations.DeleteModel(
            name='ExpressionRationnelle',
        ),
        migrations.DeleteModel(
            name='LangageRationnel',
        ),
    ]
